import type { Page, Request } from 'playwright-core';
import type { EvidenceBundle, TrackingRequestEvidence } from '../../types';
import { consentTimingValues, type ConsentTimingValues } from '../../shared/config';
import { cmpAdapterRegistry, platformRuntimeRegistry, scoreProviderCandidates, type CmpAdapterProviderId } from './adapter-registry';
import './onetrust-adapter'; import './cookiebot-adapter'; import './usercentrics-adapter'; import './didomi-adapter'; import './cookieyes-adapter'; import './sourcepoint-adapter'; import './shopify-customer-privacy-runtime';
import { createActionPlan, executeActionPlan, type ActionPlan, type ConsentInteractionStrategy, type InteractionExecutionBridge } from './action-planner';
import { buildPersistenceStorage, buildProviderContexts, buildShopifyCustomerPrivacyContext, captureBrowserConsentFacts, observeConsentFrameworksInPage, type BrowserConsentFacts } from './browser-context-builders';
import { ConsentEvidenceLedger } from './evidence-ledger';
import { ConsentAuditCodes, type AvailableAction, type BannerState, type ConsentAuditCode, type ConsentDecision, type ConsentState, type FinalConsentAuditResult, type FrameworkState, type MechanismResult, type PersistenceResult, type VerificationResult } from './domain-types';
import { detectGenericConsentMechanism, type GenericConsentDetectionResult } from './generic-consent-detector';
import { GoogleConsentModeObserver } from './google-consent-mode-observer';
import { verifySameContextReloadPersistence } from './persistence-verification';
import { verifyRequestedConsentAction, type RejectVerificationSignal } from './reject-verification-engine';
import { checkTrackingConsistency, type TrackingConsistencyResult } from './tracking-consistency';
import { buildUnknownCmpFingerprint } from './unknown-cmp-fingerprint';
import { consentV2ActionsEnabledFor, consentV2RolloutControls, type ConsentV2RolloutControls, type ConsentV2RolloutProvider } from './rollout-controls';

export interface ConsentV2SessionInput { geo: 'USA' | 'EU' | 'UK'; geo_verified: boolean | null; page_valid: boolean | null; timings?: ConsentTimingValues; access_blocked?: boolean; rollout?: ConsentV2RolloutControls; rollout_key?: string; }
export type ConsentV2Telemetry = NonNullable<EvidenceBundle['runtime']['consent_v2']>;
export interface ConsentV2SessionOutput { result: FinalConsentAuditResult; tracking: TrackingConsistencyResult; ledger: ConsentEvidenceLedger; telemetry: ConsentV2Telemetry; }

function safePath(url: string) { try { return new URL(url).pathname || '/'; } catch { return '/'; } }
function unknownState(): ConsentState { return { decision: 'ambiguous', categories: [], evidence: [], reason_codes: [ConsentAuditCodes.DETECTION_INCONCLUSIVE] }; }
function unknownBanner(): BannerState { return { surface: 'none', visibility: 'not_visible', evidence: [], reason_codes: [ConsentAuditCodes.BANNER_NOT_VISIBLE] }; }
function frameworkState(value: Awaited<ReturnType<typeof observeConsentFrameworksInPage>>): FrameworkState {
  const presence = (lifecycle: string) => lifecycle === 'absent' ? 'not_present' as const : lifecycle === 'stub_present' ? 'stub_present' as const : 'present' as const;
  return { tcf: presence(value.tcf.lifecycle), gpp: presence(value.gpp.lifecycle), usp: value.usp.present ? 'present' : 'not_present', evidence: [`tcf:${value.tcf.lifecycle}`, `gpp:${value.gpp.lifecycle}`, ...(value.usp.present ? ['usp:legacy_read_only'] : [])], reason_codes: [...value.tcf.reason_codes, ...value.gpp.reason_codes, ...value.usp.reason_codes] };
}
function frameworkMechanisms(value: FrameworkState): MechanismResult[] { return value.tcf === 'not_present' && value.gpp === 'not_present' && value.usp === 'not_present' ? [] : [{ mechanism: 'framework', detection: { status: 'verified', evidence: value.evidence, reason_codes: value.reason_codes }, provider: null, adapter_maturity: 'documentation_supported' }]; }
function genericDetection(facts: BrowserConsentFacts, frameworks: FrameworkState, gcm: GoogleConsentModeObserver): GenericConsentDetectionResult { return detectGenericConsentMechanism(facts.generic.surfaces as any, facts.generic.controls, { storage: buildPersistenceStorage(facts).map((item) => ({ storage_type: item.storage_type as 'cookie' | 'local_storage', key_name: item.key_name, exists: item.exists, consent_shaped: true })), consent_change_datalayer_event: facts.consent_commands.some((item) => item.command === 'update'), consent_mode_transition: gcm.result().lifecycle !== 'not_observed', tcf_present: frameworks.tcf !== 'not_present', gpp_present: frameworks.gpp !== 'not_present' }); }

async function selectProvider(contexts: ReturnType<typeof buildProviderContexts>, controls: ConsentV2RolloutControls) {
  const evidence = cmpAdapterRegistry.collectProviderEvidence(contexts); const candidates = scoreProviderCandidates(evidence);
  for (const candidate of candidates.filter((item) => item.high_confidence)) { const provider = candidate.provider_id as CmpAdapterProviderId; if (!controls.providers[provider].detection_enabled) continue; const detected = await cmpAdapterRegistry.get(provider)?.detect({ evidence }); if (detected?.status === 'detected') return { provider, candidates }; }
  return { provider: undefined, candidates };
}
async function providerOperations(provider: CmpAdapterProviderId | undefined, contexts: ReturnType<typeof buildProviderContexts>) {
  if (!provider) return { state: unknownState(), banner: unknownBanner(), actions: [] as AvailableAction[], persistence: null as PersistenceResult | null };
  const context = contexts.get(provider); const [state, banner, actions, persistence] = await Promise.all([cmpAdapterRegistry.invoke<ConsentState>(provider, 'state_read', { context }), cmpAdapterRegistry.invoke<BannerState>(provider, 'banner_state', { context }), cmpAdapterRegistry.invoke<AvailableAction[]>(provider, 'available_actions', { context }), cmpAdapterRegistry.invoke<PersistenceResult>(provider, 'persistence_evidence', { context })]);
  return { state: state.value || unknownState(), banner: banner.value || unknownBanner(), actions: actions.value || [], persistence: persistence.value };
}
async function shopifyOperations(facts: BrowserConsentFacts) {
  const context = buildShopifyCustomerPrivacyContext(facts); if (!context) return { mechanism: null as MechanismResult | null, state: null as ConsentState | null, banner: null as BannerState | null, actions: [] as AvailableAction[] };
  const evidence = [{ provider_id: 'shopify_customer_privacy', family: 'typed_provider_api' as const, kind: 'typed_documented_provider_api' as const, specificity: 'provider_specific' as const }, { provider_id: 'shopify_customer_privacy', family: 'provider_state' as const, kind: 'provider_state_or_event' as const, specificity: 'provider_specific' as const }];
  const detection = await platformRuntimeRegistry.get('shopify_customer_privacy')?.detect({ evidence }); if (detection?.status !== 'detected') return { mechanism: null, state: null, banner: null, actions: [] };
  const [state, banner, actions] = await Promise.all([platformRuntimeRegistry.invoke<ConsentState>('shopify_customer_privacy', 'state_read', { context }), platformRuntimeRegistry.invoke<BannerState>('shopify_customer_privacy', 'banner_state', { context }), platformRuntimeRegistry.invoke<AvailableAction[]>('shopify_customer_privacy', 'available_actions', { context })]);
  return { mechanism: { mechanism: 'commerce_privacy_runtime', detection: { status: 'verified', evidence: detection.evidence, reason_codes: detection.reason_codes }, provider: { attribution: 'identified', confidence: 'high', candidates: [{ provider_name: 'shopify', attribution: 'identified', confidence: 'high', evidence: detection.evidence, reason_codes: detection.reason_codes }], reason_codes: detection.reason_codes }, adapter_maturity: 'documentation_supported' } as MechanismResult, state: state.value, banner: banner.value, actions: actions.value || [] };
}
function providerMechanism(provider: CmpAdapterProviderId | undefined): MechanismResult[] { return provider ? [{ mechanism: 'cmp', detection: { status: 'verified', evidence: ['adapter_detection'], reason_codes: [ConsentAuditCodes.CMP_DETECTED] }, provider: { attribution: 'identified', confidence: 'high', candidates: [{ provider_name: provider, attribution: 'identified', confidence: 'high', evidence: ['adapter_detection'], reason_codes: [ConsentAuditCodes.CMP_PROVIDER_IDENTIFIED] }], reason_codes: [ConsentAuditCodes.CMP_PROVIDER_IDENTIFIED] }, adapter_maturity: cmpAdapterRegistry.getCapability(provider, 'detection').maturity }] : []; }

function telemetry(result: FinalConsentAuditResult, tracking: TrackingConsistencyResult, facts: BrowserConsentFacts, controls: ConsentV2RolloutControls, provider: CmpAdapterProviderId | undefined, conflict: boolean, blocked: boolean, actionsEnabled: boolean): ConsentV2Telemetry { const fingerprint = result.mechanisms.some((item) => item.mechanism === 'custom') ? buildUnknownCmpFingerprint({ mechanism_score: 70, provider_attribution: 'unknown_candidate', geo: null, available_actions: result.available_actions, storage_key_names: facts.storage_keys, candidate_global_names: facts.globals }) : null; const reject = result.available_actions.find((item) => item.action === 'reject_all'); return { enabled: controls.enabled, observation_only: !actionsEnabled, provider: provider || (result.mechanisms.some((item) => item.mechanism === 'custom') ? 'generic' : null), provider_confidence: provider ? 'high' : result.mechanisms.some((item) => item.mechanism === 'custom') ? 'medium' : null, provider_conflict: conflict, banner_visibility: result.banner.visibility, reject_availability: reject?.availability || 'not_present', interaction_outcome: result.interactions[0]?.outcome || 'not_attempted', verification: result.rejection_verification.status, persistence: result.persistence.status, generic_fallback: result.mechanisms.some((item) => item.mechanism === 'custom'), selector_or_action_failure: result.interactions.some((item) => item.outcome !== 'executed'), tcf_present: facts.globals.includes('__tcfapi'), gpp_present: facts.globals.includes('__gpp'), consent_mode_classification: result.google_consent_mode.evidence[0] || 'unknown', tracking_consistency: tracking.status, unknown_cmp_fingerprint: fingerprint?.fingerprint || null, geo_unverified: result.geo_verified.status !== 'verified', blocked_or_challenged: blocked }; }

/** Production composition root. Provider, framework, Shopify, and generic semantics stay in their owning modules. */
export async function runConsentV2Session(page: Page, input: ConsentV2SessionInput): Promise<ConsentV2SessionOutput> {
  const timings = input.timings || consentTimingValues(); const rollout = input.rollout || consentV2RolloutControls(); const ledger = new ConsentEvidenceLedger(); const requests: TrackingRequestEvidence[] = []; const gcm = new GoogleConsentModeObserver();
  const listener = (request: Request) => { const url = request.url(); let parsed: URL; try { parsed = new URL(url); } catch { return; } gcm.observeMeasurementRequest({ url, timestamp: Date.now() }); if (requests.length < 100) requests.push({ vendor: /facebook\.com|connect\.facebook/i.test(parsed.hostname) ? 'meta' : /google-analytics\.com/i.test(parsed.hostname) ? 'ga4' : /googleadservices|doubleclick/i.test(parsed.hostname) ? 'google_ads' : 'unknown', kind: request.resourceType() === 'script' ? 'script' : 'collection', collector: 'third_party', host: parsed.hostname, path: safePath(url), method: request.method(), phase: 'consent_v2', timestamp: Date.now(), event: parsed.searchParams.get('en') || parsed.searchParams.get('ev') || undefined }); };
  page.on('request', listener);
  try {
    ledger.append({ phase: 'baseline', source: 'page', family: 'semantic', kind: 'presence', specificity: 'generic', stability: 'stable', provenance: 'browser_api', descriptor: { exists: true } });
    const before = await captureBrowserConsentFacts(page); before.consent_commands.forEach((item) => gcm.observeGtagCall('consent', item.command, item.state));
    const frameworks = frameworkState(await observeConsentFrameworksInPage(page)); const contexts = buildProviderContexts(page, before, { tcf: frameworks.tcf !== 'not_present', gpp: frameworks.gpp !== 'not_present' }); const selection = rollout.enabled ? await selectProvider(contexts, rollout) : { provider: undefined, candidates: [] };
    const generic = genericDetection(before, frameworks, gcm); const shopify = await shopifyOperations(before); const provider = await providerOperations(selection.provider, contexts); const useGeneric = !selection.provider && rollout.providers.generic.detection_enabled && generic.status === 'detected';
    const mechanisms = input.access_blocked || !rollout.enabled ? [] : [...(shopify.mechanism ? [shopify.mechanism] : []), ...providerMechanism(selection.provider), ...(useGeneric && generic.mechanism ? [generic.mechanism] : []), ...frameworkMechanisms(frameworks)]; const initial = provider.state.decision !== 'ambiguous' ? provider.state : shopify.state || provider.state; const banner = selection.provider ? provider.banner : shopify.banner?.visibility === 'visible' ? shopify.banner : generic.action_plan.length ? { surface: generic.action_plan[0].surface_type, visibility: 'visible' as const, evidence: ['generic_detector_surface'], reason_codes: [ConsentAuditCodes.BANNER_VISIBLE] } : unknownBanner(); const actions = selection.provider ? provider.actions : shopify.actions.length ? shopify.actions : generic.actions;
    const blocked = Boolean(input.access_blocked) || !rollout.enabled;
    if (blocked) { const result = buildResult(input, mechanisms, banner, actions, initial, null, [], { status: 'inconclusive', evidence: [], reason_codes: [ConsentAuditCodes.ACTION_INCONCLUSIVE] }, { status: 'not_applicable', evidence: [], reason_codes: [ConsentAuditCodes.PERSISTENCE_NOT_APPLICABLE] }, frameworks, gcm, requests, [input.access_blocked ? ConsentAuditCodes.BLOCKED_OR_CHALLENGED : ConsentAuditCodes.DETECTION_INCONCLUSIVE]); const tracking = checkTrackingConsistency({ rejection_verification: result.rejection_verification, reject_timestamp: null, post_reject_observation_completed: false, requests }); return { result, tracking, ledger, telemetry: telemetry(result, tracking, before, rollout, undefined, false, blocked, false) }; }
    const action = actions.find((item) => item.action === 'reject_all' && (item.availability === 'direct' || item.availability === 'api_only')); const actionEnabled = consentV2ActionsEnabledFor(rollout, (selection.provider || 'generic') as ConsentV2RolloutProvider, input.rollout_key || page.url()); let after = before; let attempt: FinalConsentAuditResult['interactions'][number] | null = null; let verification: VerificationResult = { status: 'inconclusive', evidence: [], reason_codes: [ConsentAuditCodes.ACTION_INCONCLUSIVE] }; let timestamp: number | null = null;
    if (selection.provider && action && actionEnabled) { const plan = createActionPlan({ action: action.action as Exclude<typeof action.action, 'close'>, provider_or_mechanism: selection.provider, target: { surface_type: banner.surface === 'none' || banner.surface === 'unknown' ? 'banner' : banner.surface, target_ref: 'adapter_control', accessible_control: true, frame_path: ['top'], shadow_mode: 'unknown' }, eligible_strategies: action.availability === 'api_only' ? ['documented_provider_api'] : ['provider_selector'], timeout_ms: timings.postActionSettleMs, stabilization_ms: timings.postActionSettleMs, provider_api_reject_available: action.availability === 'api_only', user_facing_reject_available: action.availability === 'direct' }); const executed = await executeActionPlan(plan, adapterActionBridge(page, selection.provider, contexts, ledger, timings, initial)); attempt = executed.attempt; timestamp = Date.now(); gcm.markUserChoice(timestamp); after = await captureBrowserConsentFacts(page); const afterContexts = buildProviderContexts(page, after, { tcf: frameworks.tcf !== 'not_present', gpp: frameworks.gpp !== 'not_present' }); const afterState = (await providerOperations(selection.provider, afterContexts)).state; const adapterVerification = await cmpAdapterRegistry.invoke<VerificationResult>(selection.provider, 'verify_action', { context: afterContexts.get(selection.provider), timestamp }); const signals: RejectVerificationSignal[] = [{ family: 'interaction', rank: 'weak', relation: executed.attempt.outcome === 'executed' ? 'matches_requested' : 'unknown', observed_at: timestamp }]; if (afterState.decision === 'rejected') signals.push({ family: 'provider_state', rank: 'strong', relation: 'matches_requested', authoritative: true, observed_at: timestamp }); if (afterState.decision === 'accepted') signals.push({ family: 'provider_state', rank: 'strong', relation: 'contradicts_requested', authoritative: true, observed_at: timestamp }); if (adapterVerification.value?.evidence.length) signals.push({ family: 'provider_event', rank: 'supporting', relation: 'matches_requested', observed_at: timestamp }); verification = verifyRequestedConsentAction({ requested_action: action.action, action_timestamp: timestamp, signals, navigation_interrupted: executed.attempt.outcome === 'aborted' }); }
    const afterContexts = buildProviderContexts(page, after, { tcf: frameworks.tcf !== 'not_present', gpp: frameworks.gpp !== 'not_present' }); const resulting = (await providerOperations(selection.provider, afterContexts)).state; const persistence = await verifySameContextReloadPersistence({ meaningful_action_attempt: attempt?.outcome === 'executed', semantic_verification: verification, after_action: { semantic_state: { provider: resulting.decision, shopify_privacy: shopify.state?.decision }, storage: buildPersistenceStorage(after) }, settle_timeout_ms: timings.reloadSettleMs }, { async reloadSameContext() { const beforeUrl = page.url(); try { await page.reload({ waitUntil: 'commit' }); return { reloaded: true, same_context: true, origin_before: beforeUrl, origin_after: page.url(), navigation_interrupted: false }; } catch { return { reloaded: false, same_context: true, origin_before: beforeUrl, origin_after: page.url(), navigation_interrupted: true }; } }, async waitForSettle(timeoutMs) { try { await page.waitForLoadState('domcontentloaded', { timeout: timeoutMs }); return 'settled'; } catch { return 'timeout'; } }, async readPostReloadSnapshot() { const facts = await captureBrowserConsentFacts(page); const contextsAfterReload = buildProviderContexts(page, facts, { tcf: frameworks.tcf !== 'not_present', gpp: frameworks.gpp !== 'not_present' }); const state = (await providerOperations(selection.provider, contextsAfterReload)).state; return { semantic_state: { provider: state.decision }, storage: buildPersistenceStorage(facts) }; } });
    const result = buildResult(input, mechanisms, banner, actions, initial, resulting, attempt ? [attempt] : [], verification, persistence, frameworks, gcm, requests, [...(mechanisms.length ? [] : [ConsentAuditCodes.NO_CMP_DETECTED]), ...verification.reason_codes, ...persistence.reason_codes]); const tracking = checkTrackingConsistency({ rejection_verification: verification, reject_timestamp: timestamp, post_reject_observation_completed: persistence.status !== 'not_applicable', requests }); return { result, tracking, ledger, telemetry: telemetry(result, tracking, before, rollout, selection.provider, selection.candidates.filter((item) => item.high_confidence).length > 1, false, actionEnabled) };
  } finally { page.off('request', listener); }
}

function adapterActionBridge(page: Page, provider: CmpAdapterProviderId, contexts: ReturnType<typeof buildProviderContexts>, ledger: ConsentEvidenceLedger, timings: ConsentTimingValues, initial: ConsentState): InteractionExecutionBridge { return { async inspectTarget() { const banner = await cmpAdapterRegistry.invoke<BannerState>(provider, 'banner_state', { context: contexts.get(provider) }); const visible = banner.value?.visibility === 'visible'; return { attached: true, visible, enabled: true, surface_active: visible, frame_path: ['top'], shadow_mode: 'unknown', navigation_state: page.isClosed() ? 'interrupted' : 'idle' }; }, async executeStrategy(_plan, strategy: ConsentInteractionStrategy) { if (strategy !== 'documented_provider_api' && strategy !== 'provider_selector') return 'unsupported'; const result = await cmpAdapterRegistry.invoke<{ outcome: 'executed' | 'not_executed' }>(provider, 'reject', { context: contexts.get(provider) }); return result.value?.outcome === 'executed' ? 'executed' : result.value?.outcome === 'not_executed' ? 'not_executed' : 'unsupported'; }, appendEvidence(event) { ledger.append({ phase: 'pre_action', source: 'provider_adapter', family: 'semantic', kind: event.kind === 'state_transition' ? 'state_change' : 'semantic_control', specificity: 'provider_specific', stability: 'stable', provenance: 'adapter', provider_candidate: provider, descriptor: { exists: true } }); }, async waitForStabilization() { await page.waitForTimeout(timings.postActionSettleMs); const facts = await captureBrowserConsentFacts(page); const state = (await providerOperations(provider, buildProviderContexts(page, facts, { tcf: false, gpp: false }))).state; return { state_changed: state.decision !== initial.decision, navigation_interrupted: page.isClosed() }; } }; }
function buildResult(input: ConsentV2SessionInput, mechanisms: MechanismResult[], banner: BannerState, actions: AvailableAction[], initial: ConsentState, resulting: ConsentState | null, interactions: FinalConsentAuditResult['interactions'], verification: VerificationResult, persistence: PersistenceResult, frameworks: FrameworkState, gcm: GoogleConsentModeObserver, requests: TrackingRequestEvidence[], reasonCodes: ConsentAuditCode[]): FinalConsentAuditResult { const observed = gcm.result(); return { context_clean: { status: 'verified', evidence: ['fresh_playwright_context'], reason_codes: [] }, geo_verified: { status: input.geo_verified === true ? 'verified' : 'inconclusive', evidence: [], reason_codes: input.geo_verified === true ? [] : [ConsentAuditCodes.GEO_UNVERIFIED] }, mechanisms, banner, available_actions: actions, initial_state: initial, resulting_state: resulting, interactions, rejection_verification: verification, persistence, frameworks, google_consent_mode: { presence: observed.lifecycle === 'not_observed' ? 'not_present' : observed.classification === 'ambiguous' ? 'ambiguous' : 'present', defaults_observed: observed.commands.some((item) => item.command === 'default'), updates_observed: observed.commands.some((item) => item.command === 'update'), evidence: [observed.classification], reason_codes: observed.reason_codes }, storage_changes: [], network_signals: requests.slice(0, 100).map((item) => ({ host: item.host, path: item.path, method: item.method, phase: item.phase, signal: item.kind === 'script' ? 'script' : 'tracking' })), reason_codes: [...new Set([...(input.geo_verified === true ? [] : [ConsentAuditCodes.GEO_UNVERIFIED]), ...reasonCodes])] }; }
