export const SCANNER_VERSION = '2.1.0';
export const RULE_PACK_VERSION = '2026.08.30.1';
export const PDP_POST_LOAD_OBSERVATION_MS = 12000;
export const PDP_MIN_TRACKING_OBSERVATION_MS = 5000;
export const PDP_NAVIGATION_ATTEMPT_LIMIT = 6;
export const STRICT_DUPLICATE_WINDOW_MS = 1500;
